# Schema for the configuration files of the email confirmer user submodule.

email_confirmer_user.settings:
  type: config_object
  label: 'Email confirm user settings'
  mapping:
    user_email_change:
      type: mapping
      label: 'On user email change'
      mapping:
        enabled:
          type: boolean
          label: 'Require confirmation'
        notify_current:
          type: boolean
          label: 'Send notification to the current email address'
        consider_existent:
          type: boolean
          label: 'Consider existent confirmations'
        limit_user_realm:
          type: boolean
          label: 'Consider only user related confirmations'
    user_login:
      type: mapping
      label: 'On user log in'
      mapping:
        sync_core_confirmation:
          type: boolean
          label: 'Record email confirmation on first user log in'
        sync_core_onetimeloginlinks:
          type: boolean
          label: 'Record email confirmation when user logs in through a one-time log in link'
